#!/bin/bash

bin_dir="$(dirname "$0")"
. ${bin_dir}/.1c.inc


IB_NAME=$1

uuid=$(ib_uuid ${IB_NAME})

echo "${IB_NAME} ${uuid}"

${RAC} infobase drop --infobase=${uuid} --infobase-user=${IB_USER} --infobase-pwd=${IB_PWD}
#--drop-database
